version: "3"
services:
  geo:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace/worker
    working_dir: /workspace/worker
    environment:
      PYTHONPATH: /workspace/worker/
      MYPYPATH: /workspace/worker/
